version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "react"
        versions: ["18.3.1"]
      - dependency-name: "react-dom"
        versions: ["18.3.1"]